### ISSUE TITLE
Why there is a norm layer before go to attention

### ISSUE THREAD

**Issue by demdecuong** [pbcquoc/transformer#1]
I wonder that why there is a norm layer for the input before we go to the attention layer ?
Since i have saw the Transformer architecture there aren't any norm layer. Are there any reasons behind ?

**Comment by pbcquoc** [comment]
![](https://camo.githubusercontent.com/88e8f36ce61dedfd2491885b8df2f68c4d1f92f5/687474703a2f2f696d6775722e636f6d2f316b72463252362e706e67)

Here is original architecture of Transformer.
Did you see the Add & Norm layer

**Comment by demdecuong** [comment]
So instead of norm the sum of x and attention output. We norm it seperately before add them. Do i understand correctly ?

**Comment by pbcquoc** [comment]
yes, just normalize the input then add with previous layer, this technique we call **skip connection**
